spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile}
  resources:
    cache-period: 3600

server:
  port: 8080
  
logging:
  file: /opt/logs/100003173/apollo-portal.log

endpoints:
  shutdown:
    enabled: false
    sensitive: false #禁用密码验证
  health:
    sensitive: false

management:
  security:
    enabled: false             #忽略权限拦截


